services:
  postgres:
    image: postgres:17
    container_name: music-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: music_catalog
    ports:
      - "5432:5432"
    volumes:
      - pg17data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d music_catalog"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pg17data: